on: [push, pull_request]

name: main

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 8.x
      - run: npm install
      - name: Run tests
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: npm test
  publish-vsce:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
            node-version: 10
      - name: npm Install
        run: npm ci
      - name: VScode Publish Extension
        run: npm run deploy -- --pat ${{ secrets.VSCODE_MARKETPLACE_TOKEN }}
